import generated from './publications.json';

export interface Publication {
  title: string;
  authors: string;
  venue?: string;
  year?: number;
  citedBy?: number;
  arxivId?: string;
  doi?: string;
  dccId?: string;
  url?: string;
}

// Generated by scripts/fetch-publications.mjs from the Google Scholar profile.
// Edit that script, not this data. `source` is 'serpapi' after a real sync and
// 'seed' if the list has never been refreshed from the API.
export const publications: Publication[] = generated.publications;
export const syncedAt: string = generated.syncedAt;
export const source: string = generated.source;
