import generated from './publications.json';

export interface Publication {
  title: string;
  authors: string;
  venue?: string;
  year?: number;
  citedBy?: number;
  arxivId?: string;
  doi?: string;
  dccId?: string;
  url?: string;
}

// Generated by scripts/fetch-publications.mjs from the Google Scholar profile.
// Edit that script, not this list.
export const publications: Publication[] = generated;
